name: CD

on:
  push:
    tags:
    - "*"
    
jobs:
  tag:
    name: Deploy to WordPress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: GitHub Action for Composer
        uses: pxgamer/composer-action@v2.1.0
        with:
          command: install --optimize-autoloader --prefer-dist --no-dev
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: wk-google-analytics
